Xi_cc:
  pp14p0:
    absy1p44:
      latexcand: "#Xi_{cc}"
      #inputBkg: ../codeHF/AnalysisResults_O2_0p5.root
      #inputSig: ../codeHF/AnalysisResults_O2_0p5.root
      inputBkg: /data/Run5/results/Xicc/20200607_Xicc/AnalysisResults_O2_MB.root
      inputSig: /data/Run5/results/Xicc/20200607_Xicc/AnalysisResults_O2_enriched.root
      dirname: hf-task-xicc-mc
      normalized: 1
      varlist: ["mass", "d0Prong0", "d0Prong1", "CPA", "Y", "DecLength", "Ct", "Eta", "chi2PCA"]
      varlatex: ["inv. mass (GeV)", "d_{0} prong 0 (cm)", "d_{0} prong 1 (cm)", "cos(#theta_{p})", "rapidity", "dec. length (cm)", "c#tau (cm)", "#eta", "chi^{2} decay"]
      histonamesig: ["hmassSig", "hd0Prong0Sig", "hd0Prong1Sig", "hCPASig", "hYSig", "hDecLengthSig", "hCtSig", "hEtaSig", "hChi2PCABg"]
      histonamebkg: ["hmassBg", "hd0Prong0Bg", "hd0Prong1Bg", "hCPABg", "hYBg", "hDecLengthBg", "hCtBg", "hEtaBg", "hChi2PCABg"]
      ymin: [0.0001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      ymax: [0.1, 5., 5., 5., 5., 5., 10., 5., 5.]
      xmin: [3.55, -0.01, -0.01, 0.5, -3., 0.00001, 0., -3., 0.]
      xmax: [3.65, 0.04, 0.04, 1.1, 3., 3., 0.1, 3., 0.1]
      rebin: [1, 2, 5, 2, 5, 5, 5, 5, 5]
      dolog: [0, 1, 1, 1, 1, 1, 1, 1, 1]
      dologx: [0, 1, 0, 0, 0, 1, 0, 0, 1]
      legtoleft: [1, 1, 1, 1, 1, 1, 1, 1, 1]
Xi_c:
  pp14p0:
    absy1p44:
      latexcand: "#Xi_{c}"
      inputBkg: /data/Run5/results/Xicc/20200607_Xicc/AnalysisResults_O2_MB.root
      inputSig: /data/Run5/results/Xicc/20200607_Xicc/AnalysisResults_O2_enriched.root
      dirname: hf-task-xic-mc
      normalized: 0
      varlist: ["mass", "d0Prong0", "d0Prong1", "CPA", "DecLength", "Ct", "Eta"]
      varlatex: ["inv. mass (GeV)", "d_{0} prong 0 (cm)", "d_{0} prong 1 (cm)", "cos(#theta_{p})", "dec. length (cm)", "c#tau (cm)", "#eta"]
      histonamesig: ["hmassSig", "hd0Prong0RecSig", "hd0Prong1RecSig", "hCPARecSig", "hdeclengthRecSig", "hCtRecSig", "hEtaRecSig"]
      histonamebkg: ["hmassBg", "hd0Prong0RecBg", "hd0Prong1RecBg", "hCPARecBg", "hdeclengthRecSig", "hCtRecBg", "hEtaRecBg"]
      ymin: [0.0001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      ymax: [0.1, 5., 5., 5., 5., 10., 5.]
      xmin: [2.2, -0.01, -0.01, 0.5, 0.00001, 0., -3.]
      xmax: [2.6, 0.04, 0.04, 1.1, 3., 0.1, 3.]
      rebin: [1, 2, 5, 2, 5, 5, 5]
      dolog: [0, 1, 1, 1, 1, 1, 1]
      dologx: [0, 1, 0, 0, 1, 0, 0]
      legtoleft: [1, 1, 1, 1, 1, 1, 1]
