Xi_cc:
  pp14p0:
    absy1p44:
      latexcand: "#Xi_{cc}"
      inputBkg: /data/Run5/results/20200602_9am_loosecuts/AnalysisResults_O2_MB.root
      inputSig: /data/Run5/results/20200602_9am_loosecuts/AnalysisResults_O2_enriched.root
      dirname: hf-task-xicc-mc
      normalized: 1
      varlist: ["mass", "d0Prong0", "d0Prong1", "CPA", "Y", "DecLength", "Ct", "Eta", "chi2PCA"]
      varlatex: ["inv. mass (GeV)", "d_{0} prong 0 (cm)", "d_{0} prong 1 (cm)", "cos(#theta_{p})", "rapidity", "dec. length (cm)", "c#tau (cm)", "#eta", "chi^{2} decay"]
      histonamesig: ["hmassSig", "hd0Prong0Sig", "hd0Prong1Sig", "hCPASig", "hYSig", "hDecLengthSig", "hCtSig", "hEtaSig", "hChi2PCABg"]
      histonamebkg: ["hmassBg", "hd0Prong0Bg", "hd0Prong1Bg", "hCPABg", "hYBg", "hDecLengthBg", "hCtBg", "hEtaBg", "hChi2PCABg"]
      ymin: [0.0001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      ymax: [0.4, 5., 5., 5., 5., 5., 10., 5., 5.]
      xmin: [3.2, -0.01, -0.01, 0.5, -3., 0.00001, 0., -3., 0.]
      xmax: [4., 0.04, 0.04, 1.1, 3., 3., 0.1, 3., 0.1]
      rebin: [5, 2, 5, 2, 5, 5, 5, 5, 5]
      dolog: [0, 1, 1, 1, 1, 1, 1, 1, 1]
      dologx: [0, 1, 0, 0, 0, 1, 0, 0, 1]
      legtoleft: [1, 1, 1, 1, 1, 1, 1, 1, 1]
