Xi_cc:
  pp14p0:
    absy1p44:
      latexcand: "#Xi_{cc}"
      inputBkg: /data/Run5/results/AnalysisResults_O2_MB.root
      inputSig: /data/Run5/results/AnalysisResults_O2_enriched.root
      dirname: hf-task-xicc-mc
      normalized: 1
      varlist: ["mass", "d0Prong0", "d0Prong1", "absCPA", "Y",
                "DecLength", "Ct", "Eta"]
      varlatex: ["inv. mass (GeV)", "d_{0} prong 1 (cm)",
                 "d_{0} prong 1 (cm)", "|cos(#theta_{p})|",
                 "rapidity", "dec. length (cm)", "c#tau (cm)", "#eta"]
      histonamesig: ["hmassSig", "hd0Prong0Sig", "hd0Prong1Sig",
                     "hCPASig", "hYSig", "hDecLengthSig", "hCtSig", "hEtaSig"]
      histonamebkg: ["hmassBg", "hd0Prong0Bg", "hd0Prong1Bg",
                     "hCPABg", "hYBg", "hDecLengthBg", "hCtBg", "hEtaBg"]
      ymin: [0.0001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      ymax: [5., 5., 5., 5., 5., 5., 10., 5.]
      xmin: [3.2, -0.04, -0.04, 0., -3., 0.00001, 0.001, -3.]
      xmax: [4., 0.04, 0.04, 1.1, 3., 3., 10., 3.]
      rebin: [5, 1, 1, 2, 2, 2, 2, 2]
      dolog: [1, 1, 1, 1, 1, 1, 1, 1]
      dologx: [0, 0, 0, 1, 0, 1, 1, 0]
      legtoleft: [1, 1, 1, 1, 1, 1, 1, 1]
