---
# https://github.com/marketplace/actions/clang-format-lint
name: ClangFormat
on: [push, pull_request]
permissions: {}
jobs:
  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clang Format
        id: clang
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          #source: '.'
          #exclude: './third_party ./external'
          extensions: 'C,c,c++,cc,cl,cpp,cu,cuh,cxx,cxx.in,h,h++,hh,h.in,hpp,hxx,inc,inl,macro,json'
          clangFormatVersion: 16
          style: file
          inplace: true

      # Set a results status = 0 if no changes, = 1 if formatted
      - name: Set result status
        id: clang-result
        run: |
          status=0
          if ! git diff --quiet; then
            status=1
          fi
          echo "status=$status" >> "$GITHUB_OUTPUT"

        # Create pull request if applicable (for now works only on PR from same repository, not from forks)
      - name: Print PR condition
        run: |
          # Print the condition
          echo "${{ steps.clang-result.outputs.status }} == 1 && (${{ github.event_name }} == 'push' || ${{ github.event.pull_request.head.repo.full_name }} == ${{ github.repository }})"
      - name: Create Pull Request with applied fixes
        id: cpr
        if: steps.clang-result.outputs.status == 1 && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          commit-message: "[Clang format] Apply linters automatic fixes"
          title: "[Clang format] Apply linters automatic fixes"
          body: "Please merge this pull request to apply automatic fixes by Clang format."
          labels: bot
          branch: patch-${{ github.workflow }}-${{ github.ref_name }}
          delete-branch: true
      - name: Create PR output
        if: steps.clang-result.outputs.status == 1 && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
        run: |
          echo "::error::Merge pull request ${{ steps.cpr.outputs.pull-request-url }} to apply automatic fixes."
          exit 1
